### PR TITLE
Remove large chunks of unused code

### PR DESCRIPTION
**Pull request by Saalvage**
All not used by DCS and not tangibly related to writing a Discord bot. One or two things might actually be useful, so this deserves a lookover for anything we wanna keep.

Current candidates for keeping around:
- `MemoryBuffer` to upload files

### CODE REVIEW

**Comment by JBraunsmaJr** [comment]
I agree with this assessment

**Comment by Saalvage** [comment]
This should get some momentum!

**Comment by Lulalaby** [comment]
Yeah let's keep memory buffer for now. It could be useful

**Comment by KazutoKashima** [comment]
Yeah I agree with keeping the membuff, I'm not *too* familiar with DCS but from experience in other projects it should help debug amongst other things ^^

**Pull request closed without merging**
