### PR TITLE
Logging injected via DI

### PR DESCRIPTION
**Pull request by JBraunsmaJr**
# Description

When DCS is created and is given a ServiceProvider, it shall utilize both the LoggerFactory and Logger implementations available to it.

This eliminates the opinion based system we implemented using Serilog.  If you're using DI you have to opt into a specific logging system. By default DI uses Microsoft. If you want Serilog you need to add it (not hard to do).

Fixes # (issue)

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

Created a test-bot with a few test-commands that will output using a DI-provided Logger.

When using the default pipeline, in the project-template we have, it gives the Microsoft based implementation.
When using serilog it uses the Serilog version. Easy to tell since the formatting is different.

This will require a documentation update on how to add Serilog which is 1 line of code, or more if you prefer spacing things over multiple lines for readability.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by JBraunsmaJr** [comment]
This will close #125

**Review by Lulalaby — APPROVED** [review]
That's it?

**Comment by JBraunsmaJr** [comment]
Yup... shockingly simple isn't it lol.

**Comment by Lulalaby** [comment]
I am.. yeah it is.
It seems I always tend to use the hard way.

**Comment by JBraunsmaJr** [comment]
I was a bit surprised that it was this simple as well. It seemed too good to be true. Spent more time learning Serilog and how to add it to DI than I did on DCS itself lol.

**Review by Lulalaby — APPROVED** [review]

**Pull request merged**
