### PR TITLE
Fixed Naming

### PR DESCRIPTION
**Pull request by JBraunsmaJr**
# Description

Fixed naming. Removed unused using statement

### CODE REVIEW

**Review by KazutoKashima — APPROVED** [review]
Lgtm

**Comment by Lulalaby** [comment]
Arigatou. Will take care of it later. Planned a lil rewrite of the handling.

**Comment by JBraunsmaJr** [comment]
I'd be more okay with this being idle if this was anything but the main branch. We spent a lot of time on standardizing things and getting our configuration in the right place. Main branch should be a reflection of the standards we set for ourselves. Otherwise this is how code-bases slowly drift away and get to a point that it did lol. Also, we more than anyone need to adhere to our standards otherwise we set precedence for others to do their thang

**Comment by Lulalaby** [comment]
yeah I totally agree and I am sorry at the same time. 
My head was too much at pycord the last days

**Pull request merged**
