### PR TITLE
Implement AutoDefer

### PR DESCRIPTION
**Pull request by Lulalaby**
Auto-Defer slash and context menu commands if requested.

### CODE REVIEW

**Review by KazutoKashima — APPROVED** [review]
Lgtm

Note on my ocd: I'd have done `if(!!AutoDefer) {}` but that's just me 😂

**Comment by Lulalaby** [comment]
> Lgtm
> 
> Note on my ocd: I'd have done `if(!!AutoDefer) {}` but that's just me 😂

Silly

**Comment by KazutoKashima** [comment]
I am not! *pout*

**Review by cking — APPROVED** [review]

**Comment by cking** [comment]
> I am not! _pout_

Silly

**Pull request merged**
