### PR TITLE
9.8.5

### PR DESCRIPTION
**Pull request by Lulalaby**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by JBraunsmaJr** [comment]
I'm confused as to why we were requested to review something that ultimately got merged minutes after the request.

**Comment by Lulalaby** [comment]
Review assignment happens automatically

**Comment by Lulalaby** [comment]
It wasn't planned to add a review anyways.

**Comment by KazutoKashima** [comment]
Lmao, it do be like that, that's why I set it to be manual not automatic

**Pull request merged**
