### PR TITLE
Fix Namespaces

### PR DESCRIPTION
**Pull request by TheXorog**
This fixes [T204](https://aitsys.dev/T204).

### CODE REVIEW

**Comment by TheXorog** [comment]
Modified the enums for now, still have to check namespaces for other files.

**Comment by TheXorog** [comment]
Checked Main Project, couldn't find any more here.

**Comment by TheXorog** [comment]
Skipped ApplicationCommands and CommandsNext, Lala said so 💃

**Comment by TheXorog** [comment]
Configuration, Hosting, Interactivity all look fine as well.

ApplicationCommands, CommandsNext and Lavalink are gonna require additional checking in the future. Lala instructed me to skip those 3 for now.

**Comment by Lulalaby** [comment]
On-hold till docs workflow is fixed

**Pull request closed without merging**
