### PR TITLE
[WIP][Feature] IConfiguration implementation

### PR DESCRIPTION
**Pull request by JBraunsmaJr**
Added: Methods to easily extract Library configs from IConfiguration
Added: Unit tests to validate functionality

# Description

As discussed the HttpTimeout had a weird value of 100, adjusted value to 20 seconds so I can test default values

To prepare for Web host support, added a separate package to simplify configuration loading from IConfiguration instances.
The approach is to instantiate an instance of the described config and inject/override user defined values from the config into said instance.

This approach works with complex objects unlike the default binder for IConfiguration. 

Assumes we will group DisCatSharp based configs as seen below... just to keep things together

```json
{
   "Logging": {
        "LogLevel": {
            "Default": "Debug",
            "System": "Information",
            "Microsoft": "Information"
        }
    },

    "DisCatSharp": {
        "Discord": { 
            "HttpTimeout": "00:05:00"
        },

       "Interactivity": { 
          "imagine stuff": "here"
      }
   }
}
```

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# How Has This Been Tested?

Added unit tests which validate functionality proposed in PR. Open to suggestions on more tests to add.

# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Lulalaby** [comment]
I like that!

**Comment by Lulalaby** [comment]
@geferon relates to Task https://aitsys.dev/T48 I guess

**Review by Lulalaby — APPROVED** [review]
LGTM but waiting for feedback of geferon

**Comment by JBraunsmaJr** [comment]
Don't merge yet -- adding alternative methods to extract a config so we can cover some use cases

**Comment by JBraunsmaJr** [comment]
#35 might as well combine the two

**Pull request closed without merging**
