### PR TITLE
Faster locking through .NET 9's System.Threading.Lock

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**

### CODE REVIEW

**Review by Lulalaby — COMMENTED** [review]
Many thanks. Will take a look when I'm back home.
Quick question, is that backwards compatible, since we target net7, net8 & net9 (actually I'm not sure if we even target net 7 anymore)?

**Comment by MarkCiliaVincenti** [comment]
> Many thanks. Will take a look when I'm back home. Quick question, is that backwards compatible, since we target net7, net8 & net9 (actually I'm not sure if we even target net 7 anymore)?

Yes it is. It's a backport of the new System.Threading.Lock. The performance pre net9 will be unaffected but the performance on net9+ will be improved.

**Comment by Lulalaby** [comment]
Hey there!

I've given this PR many thoughts and came to the conclusion that it's personally a too big possible security risk to depend on such a small package.
Nothing personal, but I would prefer adapting the literally one-file "fix" into DisCatSharp.Common directly, instead of depending on the package.
No hard feelings please.

**Comment by MarkCiliaVincenti** [comment]
You can. It has an MIT licence. But it goes without saying you won't get potential updates.

**Comment by Lulalaby** [comment]
That's fine
I'll leave the PR open for a while tho to speak with the other maintainers again

**Comment by MarkCiliaVincenti** [comment]
I'll amend the PR tomorrow.

**Comment by Lulalaby** [comment]
Sounds good. We probably still take some time because both me and the other project lead are kinda mid burnout 😅

**Comment by MarkCiliaVincenti** [comment]
OK done @Lulalaby

**Review by Lulalaby — APPROVED** [review]
Hey! I've reconsidered this pr and will go ahead with the dependency instead, makes it easier for us to automatically manage the updates + doesn't add a new license part.
Thank you!

**Comment by MarkCiliaVincenti** [comment]
Beautiful! But you should look at the original commit which conditionally doesn't add the dependency for net9

**Comment by Lulalaby** [comment]
"conditionally doesn't add the dependency for net9" A bit confused about that part, do you mean the change from me with the langversion through Package.targets?

**Review by TheXorog — APPROVED** [review]
@Lulalaby Please disable renovate's auto updates for the newly added package as a security measure.

Thanks for the PR!

**Comment by Lulalaby** [comment]
Oh I learned something new today! Haha thanks

**Comment by Lulalaby** [comment]
> @Lulalaby Please disable renovate's auto updates for the newly added package as a security measure.
> 
> Thanks for the PR!

https://github.com/Aiko-IT-Systems/DisCatSharp/commit/7a6633a06087d0e92696280fe90081708083f30f

**Pull request merged**
